my_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("sample_app/", include("sample_app.urls")),
    path("admin/", admin.site.urls),
]

sample_app/urls.py
"""URLと処理を紐づけるモジュールです。"""

from django.urls import path

from sample_app import views

app_name = "sample_app"
urlpatterns = [
    path("post/create/", views.create_post, name="create_post"),  # 作成
    path("post/edit/<int:post_id>/", views.edit_post, name="edit_post"),  # 修正
    path("post/", views.read_post, name="read_post"),  # 一覧表示
    path("post/delete/<int:post_id>/", views.delete_post, name="delete_post"),  # 削除
]

sample_app/models.py
"""このモジュールは、ソーシャルメディアの投稿を管理するためのDjangoモデルを定義します。

クラス:
    Post: ユーザーが投稿するソーシャルメディアの投稿を表すモデル。
"""

from django.db import models


class Post(models.Model):
    """ユーザーが投稿したソーシャルメディアの投稿を表すモデル。

    属性:
        name: 投稿者の名前を表します。
        micropost: 投稿内容を表します。
    """

    name: str = models.CharField("user name", max_length=15)
    micropost: str = models.CharField("tweet", max_length=140, blank=True)

    def __str__(self) -> str:
        """投稿者の名前を文字列として返します。

        戻り値:
            str: 投稿者の名前。
        """
        return self.name

sample_app/views.py
"""このモジュールは、Djangoアプリケーション「sample_app」のビューを定義します。

ユーザーが投稿データを操作するための機能を提供します。

クラス:
    PostForm: Postモデルに基づくフォームを提供します。

関数:
    create_post: 新しい投稿を作成します。
    read_post: 投稿データの一覧を表示します。
    edit_post: 指定された投稿を編集します。
    delete_post: 指定された投稿を削除します。
"""

from django.forms import ModelForm
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from sample_app.models import Post


def create_post(request: HttpRequest) -> HttpResponse:
    """新規に投稿を作成する。

    Args:
        request: HTTPリクエストオブジェクト。

    Returns:
        HttpResponse: テンプレートをレンダリングしたレスポンス。

    """
    # オブジェクトを新規作成する
    post = Post()

    # ページロード時
    if request.method == "GET":
        # 新規作成オブジェクトにより form を作成
        form = PostForm(instance=post)

        # ページロード時は form を Template に渡す
        return render(
            request,
            "sample_app/post_form.html",  # 呼び出す Template
            {"form": form},
        )  # Template に渡すデータ

    # 実行ボタン押下時
    if request.method == "POST":
        # POST されたデータにより form を作成
        form = PostForm(request.POST, instance=post)

        # 入力されたデータのバリデーション
        if form.is_valid():
            # チェック結果に問題なければデータを作成する
            post = form.save(commit=False)
            post.save()

        return redirect("sample_app:read_post")
    return None


def read_post(request: HttpRequest) -> HttpResponse:
    """データの一覧を表示する。

    Args:
        request: HTTPリクエストオブジェクト。

    Returns:
        HttpResponse: テンプレートをレンダリングしたレスポンス。

    """
    # 全オブジェクトを取得
    posts = Post.objects.all().order_by("id")
    return render(
        request,
        "sample_app/post_list.html",  # 呼び出す Template
        {"posts": posts},
    )  # Template に渡すデータ


def edit_post(request: HttpRequest, post_id: int) -> HttpResponse:
    """指定された投稿を更新し、投稿一覧画面にリダイレクトする。

    Args:
        request: HTTPリクエストオブジェクト。
        post_id: 更新対象の投稿のID。

    Returns:
        HttpResponse: 投稿一覧画面へのリダイレクトレスポンス。

    """
    # IDを引数に、対象オブジェクトを取得
    post = get_object_or_404(Post, pk=post_id)

    # ページロード時
    if request.method == "GET":
        # 対象オブジェクトにより form を作成
        form = PostForm(instance=post)

        # ページロード時は form とデータIDを Template に渡す
        return render(
            request,
            "sample_app/post_form.html",  # 呼び出す Template
            {"form": form, "post_id": post_id},
        )  # Template に渡すデータ

    # 実行ボタン押下時
    if request.method == "POST":
        # POST されたデータにより form を作成
        form = PostForm(request.POST, instance=post)

        # 入力されたデータのバリデーション
        if form.is_valid():
            # チェック結果に問題なければデータを更新する
            post = form.save(commit=False)
            post.save()

        # 実行ボタン押下時は処理実行後、一覧画面にリダイレクトする
        return redirect("sample_app:read_post")
    return None


def delete_post(_request: HttpRequest, post_id: int) -> HttpResponse:
    """指定された投稿を削除し、投稿一覧画面にリダイレクトする。

    Args:
        request: HTTPリクエストオブジェクト。
        post_id: 削除対象の投稿のID。

    Returns:
        HttpResponse: 投稿一覧画面へのリダイレクトレスポンス。

    """
    # 対象のオブジェクトを取得
    post = get_object_or_404(Post, pk=post_id)
    post.delete()

    # 削除リクエスト時は削除実行後、一覧表示画面へリダイレクトする
    return redirect("sample_app:read_post")


class PostForm(ModelForm):
    """フォーム定義"""

    class Meta:
        """Postモデルと連携するフォームの設定を定義する内部クラス。"""

        model = Post
        # fields は models.py で定義している変数名
        fields = ("name", "micropost")

sample_app/templates/sample_app/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post Form</title>
</head>
<body>
    <h4>Post の編集</h4>
    {% if post_id %}
    <form action="{% url 'sample_app:edit_post' post_id=post_id %}" method="post">
    {% else %}
    <form action="{% url 'sample_app:create_post' %}" method="post">
    {% endif %}
      {% csrf_token %}
      {{ form }}
          <button type="submit">送信</button>
    </form>
    <a href="{% url 'sample_app:read_post' %}">戻る</a>
</body>
</html>

sample_app/templates/sample_app/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post lists</title>
</head>
<body>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>User Name</th>
        <th>Post</th>
      </tr>
    </thead>
    <tbody>
      {% for post in posts %}
      <tr>
        <th>{{ post.id }}</th>
        <td>{{ post.name }}</td>
        <td>{{ post.micropost }}</td>
        <td>
          <a href="{% url 'sample_app:edit_post' post_id=post.id %}">修正</a>
          <a href="{% url 'sample_app:delete_post' post_id=post.id %}">削除</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <a href="{% url 'sample_app:create_post' %}">作成</a>
</body>
</html>